#!/bin/sh
xsetwacom set "Wacom Bamboo Pen Pen stylus" Area 0 0 14720 9200
xsetwacom set "Wacom Bamboo Pen Pen stylus" Rotate None
xsetwacom set "Wacom Bamboo Pen Pen stylus" RawSample 4
# This file was generated by WacomAreaX11
# https://github.com/yellowsink/WacomAreaX11