#!/bin/sh
xsetwacom set "Wacom Bamboo Pen Pen stylus" Area 5560 2012 7585 5612
xsetwacom set "Wacom Bamboo Pen Pen stylus" Rotate Ccw
xsetwacom set "Wacom Bamboo Pen Pen stylus" RawSample 1
# This file was generated by WacomAreaX11
# https://github.com/yellowsink/WacomAreaX11