#!/bin/sh
# This file was generated by the WacomAreaX11
# https://github.com/yellowsink/WacomAreaX11
xsetwacom set "Wacom Bamboo Pen Pen stylus" Area 5460 1868 7597 5668
xsetwacom set "Wacom Bamboo Pen Pen stylus" Rotate Ccw
xsetwacom set "Wacom Bamboo Pen Pen stylus" RawSample 1