# {{{
# Generated by zgenom.
# This file will be overwritten the next time you run zgenom save!

export PMSPEC=0fiPs
export ZPFX=/home/cain/.zgenom/polaris

ZGENOM_PLUGINS=(hkupty/ssh-agent/___ zsh-users/zsh-autosuggestions/___ zsh-users/zsh-completions/___ zsh-users/zsh-history-substring-search/___ romkatv/powerlevel10k/___ zsh-users/zsh-syntax-highlighting/___)

ZSH=/home/cain/.zgenom/sources/ohmyzsh/ohmyzsh/___

# ### Plugins & Completions
fpath=(/home/cain/.zgenom/sources/hkupty/ssh-agent/___ ${fpath})

# ### General modules
typeset -ga zsh_loaded_plugins
zsh_loaded_plugins+=( "hkupty/ssh-agent" )
ZERO="/home/cain/.zgenom/sources/hkupty/ssh-agent/___/ssh-agent.plugin.zsh" source "/home/cain/.zgenom/sources/hkupty/ssh-agent/___/ssh-agent.plugin.zsh"

# }}}
